//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public Farmer()
        {
            this.Equipments = new HashSet<Equipment>();
            this.Loans = new HashSet<Loan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
