//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_SmartFarmEntities : DbContext
    {
        public Db_SmartFarmEntities()
            : base("name=Db_SmartFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Farmer> Farmers { get; set; }
        public DbSet<Loan> Loans { get; set; }
    }
}
